const STATE_CITY_DATA = {
  "AL": [
    "Birmingham",
    "Montgomery",
    "Mobile",
    "Huntsville",
    "Tuscaloosa",
    "Auburn",
    "Dothan",
    "Hoover",
    "Decatur",
    "Florence",
    "Gadsden"
  ],
  "AK": [
    "Anchorage",
    "Fairbanks",
    "Juneau",
    "Sitka",
    "Ketchikan",
    "Wasilla",
    "Kenai",
    "Kodiak",
    "Palmer"
  ],
  "AZ": [
    "Phoenix",
    "Tucson",
    "Mesa",
    "Chandler",
    "Scottsdale",
    "Glendale",
    "Tempe",
    "Peoria",
    "Surprise",
    "Yuma",
    "Flagstaff",
    "Prescott",
    "Sedona"
  ],
  "AR": [
    "Little Rock",
    "Fayetteville",
    "Fort Smith",
    "Springdale",
    "Jonesboro",
    "Rogers",
    "Conway",
    "Bentonville",
    "Hot Springs",
    "Pine Bluff"
  ],
  "CA": [
    "Los Angeles",
    "San Diego",
    "San Jose",
    "San Francisco",
    "Fresno",
    "Sacramento",
    "Long Beach",
    "Oakland",
    "Bakersfield",
    "Anaheim",
    "Santa Ana",
    "Riverside",
    "Stockton",
    "Irvine",
    "Chula Vista",
    "Fremont",
    "San Bernardino",
    "Modesto",
    "Fontana",
    "Santa Clarita",
    "Oxnard",
    "Moreno Valley",
    "Glendale",
    "Huntington Beach",
    "Santa Rosa",
    "Elk Grove",
    "Oceanside",
    "Rancho Cucamonga",
    "Ontario",
    "Lancaster",
    "Palmdale",
    "Corona",
    "Salinas",
    "Pomona",
    "Torrance",
    "Pasadena",
    "Escondido",
    "Sunnyvale",
    "Orange",
    "Fullerton",
    "Thousand Oaks",
    "Visalia",
    "Concord",
    "Simi Valley",
    "Victorville",
    "Berkeley",
    "Santa Monica",
    "Santa Barbara",
    "Monterey",
    "Napa",
    "Palm Springs",
    "Yosemite Valley",
    "Lake Tahoe"
  ],
  "CO": [
    "Denver",
    "Colorado Springs",
    "Aurora",
    "Fort Collins",
    "Lakewood",
    "Thornton",
    "Arvada",
    "Westminster",
    "Pueblo",
    "Boulder",
    "Greeley",
    "Longmont",
    "Loveland",
    "Grand Junction",
    "Aspen",
    "Vail",
    "Durango"
  ],
  "CT": [
    "Bridgeport",
    "New Haven",
    "Stamford",
    "Hartford",
    "Waterbury",
    "Norwalk",
    "Danbury",
    "New Britain",
    "Bristol",
    "Meriden",
    "Mystic"
  ],
  "DE": [
    "Wilmington",
    "Dover",
    "Newark",
    "Middletown",
    "Smyrna",
    "Milford",
    "Rehoboth Beach"
  ],
  "FL": [
    "Jacksonville",
    "Miami",
    "Tampa",
    "Orlando",
    "St. Petersburg",
    "Hialeah",
    "Port St. Lucie",
    "Tallahassee",
    "Cape Coral",
    "Fort Lauderdale",
    "Pembroke Pines",
    "Hollywood",
    "Gainesville",
    "Coral Springs",
    "Clearwater",
    "Palm Bay",
    "West Palm Beach",
    "Lakeland",
    "Pompano Beach",
    "Miami Beach",
    "Daytona Beach",
    "Key West",
    "Naples",
    "Sarasota",
    "Fort Myers",
    "Boca Raton",
    "Destin"
  ],
  "GA": [
    "Atlanta",
    "Augusta",
    "Columbus",
    "Macon",
    "Savannah",
    "Athens",
    "Sandy Springs",
    "Roswell",
    "Johns Creek",
    "Albany",
    "Warner Robins",
    "Valdosta",
    "Marietta",
    "Alpharetta",
    "Brunswick"
  ],
  "HI": [
    "Honolulu",
    "Hilo",
    "Kailua",
    "Kapolei",
    "Kaneohe",
    "Waipahu",
    "Lahaina",
    "Kihei"
  ],
  "ID": [
    "Boise",
    "Meridian",
    "Nampa",
    "Idaho Falls",
    "Pocatello",
    "Caldwell",
    "Coeur d'Alene",
    "Twin Falls",
    "Lewiston"
  ],
  "IL": [
    "Chicago",
    "Aurora",
    "Naperville",
    "Joliet",
    "Rockford",
    "Springfield",
    "Elgin",
    "Peoria",
    "Champaign",
    "Waukegan",
    "Cicero",
    "Bloomington",
    "Evanston",
    "Schaumburg",
    "Decatur"
  ],
  "IN": [
    "Indianapolis",
    "Fort Wayne",
    "Evansville",
    "South Bend",
    "Carmel",
    "Fishers",
    "Bloomington",
    "Hammond",
    "Gary",
    "Lafayette",
    "Muncie",
    "Terre Haute"
  ],
  "IA": [
    "Des Moines",
    "Cedar Rapids",
    "Davenport",
    "Sioux City",
    "Iowa City",
    "Waterloo",
    "Ames",
    "West Des Moines",
    "Council Bluffs",
    "Dubuque"
  ],
  "KS": [
    "Wichita",
    "Overland Park",
    "Kansas City",
    "Olathe",
    "Topeka",
    "Lawrence",
    "Shawnee",
    "Manhattan",
    "Lenexa",
    "Salina"
  ],
  "KY": [
    "Louisville",
    "Lexington",
    "Bowling Green",
    "Owensboro",
    "Covington",
    "Richmond",
    "Georgetown",
    "Florence",
    "Frankfort",
    "Paducah"
  ],
  "LA": [
    "New Orleans",
    "Baton Rouge",
    "Shreveport",
    "Lafayette",
    "Lake Charles",
    "Kenner",
    "Bossier City",
    "Monroe",
    "Alexandria",
    "Natchitoches"
  ],
  "ME": [
    "Portland",
    "Lewiston",
    "Bangor",
    "South Portland",
    "Auburn",
    "Biddeford",
    "Augusta",
    "Saco",
    "Westbrook",
    "Bar Harbor"
  ],
  "MD": [
    "Baltimore",
    "Frederick",
    "Rockville",
    "Gaithersburg",
    "Bowie",
    "Hagerstown",
    "Annapolis",
    "College Park",
    "Salisbury",
    "Ocean City"
  ],
  "MA": [
    "Boston",
    "Worcester",
    "Springfield",
    "Cambridge",
    "Lowell",
    "Brockton",
    "Quincy",
    "Lynn",
    "New Bedford",
    "Somerville",
    "Salem",
    "Plymouth",
    "Cape Cod"
  ],
  "MI": [
    "Detroit",
    "Grand Rapids",
    "Warren",
    "Sterling Heights",
    "Ann Arbor",
    "Lansing",
    "Flint",
    "Dearborn",
    "Livonia",
    "Troy",
    "Kalamazoo",
    "Traverse City",
    "Mackinaw City"
  ],
  "MN": [
    "Minneapolis",
    "Saint Paul",
    "Rochester",
    "Duluth",
    "Bloomington",
    "Brooklyn Park",
    "Plymouth",
    "Woodbury",
    "Lakeville",
    "Mankato"
  ],
  "MS": [
    "Jackson",
    "Gulfport",
    "Southaven",
    "Biloxi",
    "Hattiesburg",
    "Olive Branch",
    "Tupelo",
    "Meridian",
    "Greenville",
    "Oxford"
  ],
  "MO": [
    "Kansas City",
    "St. Louis",
    "Springfield",
    "Columbia",
    "Independence",
    "Lee's Summit",
    "O'Fallon",
    "St. Joseph",
    "St. Charles",
    "Branson"
  ],
  "MT": [
    "Billings",
    "Missoula",
    "Great Falls",
    "Bozeman",
    "Butte",
    "Helena",
    "Kalispell",
    "Havre",
    "Whitefish"
  ],
  "NE": [
    "Omaha",
    "Lincoln",
    "Bellevue",
    "Grand Island",
    "Kearney",
    "Fremont",
    "Hastings",
    "North Platte",
    "Norfolk"
  ],
  "NV": [
    "Las Vegas",
    "Henderson",
    "Reno",
    "North Las Vegas",
    "Sparks",
    "Carson City",
    "Elko",
    "Boulder City",
    "Mesquite"
  ],
  "NH": [
    "Manchester",
    "Nashua",
    "Concord",
    "Derry",
    "Dover",
    "Rochester",
    "Salem",
    "Portsmouth",
    "Keene"
  ],
  "NJ": [
    "Newark",
    "Jersey City",
    "Paterson",
    "Elizabeth",
    "Edison",
    "Woodbridge",
    "Lakewood",
    "Toms River",
    "Hamilton",
    "Trenton",
    "Princeton",
    "Atlantic City",
    "Cape May"
  ],
  "NM": [
    "Albuquerque",
    "Las Cruces",
    "Rio Rancho",
    "Santa Fe",
    "Roswell",
    "Farmington",
    "Clovis",
    "Hobbs",
    "Taos"
  ],
  "NY": [
    "New York",
    "Buffalo",
    "Rochester",
    "Yonkers",
    "Syracuse",
    "Albany",
    "New Rochelle",
    "Mount Vernon",
    "Schenectady",
    "Utica",
    "Ithaca",
    "Binghamton",
    "Niagara Falls",
    "Saratoga Springs"
  ],
  "NC": [
    "Charlotte",
    "Raleigh",
    "Greensboro",
    "Durham",
    "Winston-Salem",
    "Fayetteville",
    "Cary",
    "Wilmington",
    "High Point",
    "Concord",
    "Asheville",
    "Chapel Hill",
    "Outer Banks"
  ],
  "ND": [
    "Fargo",
    "Bismarck",
    "Grand Forks",
    "Minot",
    "West Fargo",
    "Williston",
    "Dickinson",
    "Jamestown"
  ],
  "OH": [
    "Columbus",
    "Cleveland",
    "Cincinnati",
    "Toledo",
    "Akron",
    "Dayton",
    "Parma",
    "Canton",
    "Youngstown",
    "Lorain",
    "Athens",
    "Sandusky"
  ],
  "OK": [
    "Oklahoma City",
    "Tulsa",
    "Norman",
    "Broken Arrow",
    "Lawton",
    "Edmond",
    "Moore",
    "Midwest City",
    "Enid",
    "Stillwater"
  ],
  "OR": [
    "Portland",
    "Eugene",
    "Salem",
    "Gresham",
    "Hillsboro",
    "Bend",
    "Beaverton",
    "Medford",
    "Springfield",
    "Corvallis",
    "Astoria",
    "Cannon Beach"
  ],
  "PA": [
    "Philadelphia",
    "Pittsburgh",
    "Allentown",
    "Erie",
    "Reading",
    "Scranton",
    "Bethlehem",
    "Lancaster",
    "Harrisburg",
    "Altoona",
    "York",
    "State College",
    "West Chester",
    "Gettysburg"
  ],
  "RI": [
    "Providence",
    "Warwick",
    "Cranston",
    "Pawtucket",
    "East Providence",
    "Woonsocket",
    "Newport",
    "Narragansett"
  ],
  "SC": [
    "Charleston",
    "Columbia",
    "North Charleston",
    "Mount Pleasant",
    "Rock Hill",
    "Greenville",
    "Summerville",
    "Sumter",
    "Hilton Head Island",
    "Myrtle Beach"
  ],
  "SD": [
    "Sioux Falls",
    "Rapid City",
    "Aberdeen",
    "Brookings",
    "Watertown",
    "Mitchell",
    "Yankton",
    "Pierre",
    "Deadwood"
  ],
  "TN": [
    "Nashville",
    "Memphis",
    "Knoxville",
    "Chattanooga",
    "Clarksville",
    "Murfreesboro",
    "Franklin",
    "Jackson",
    "Johnson City",
    "Gatlinburg"
  ],
  "TX": [
    "Houston",
    "San Antonio",
    "Dallas",
    "Austin",
    "Fort Worth",
    "El Paso",
    "Arlington",
    "Corpus Christi",
    "Plano",
    "Laredo",
    "Lubbock",
    "Garland",
    "Irving",
    "Amarillo",
    "Grand Prairie",
    "McKinney",
    "Frisco",
    "Brownsville",
    "Pasadena",
    "Killeen",
    "Waco",
    "Denton",
    "Midland",
    "Odessa",
    "Galveston"
  ],
  "UT": [
    "Salt Lake City",
    "West Valley City",
    "Provo",
    "West Jordan",
    "Orem",
    "Sandy",
    "Ogden",
    "St. George",
    "Layton",
    "Logan",
    "Moab",
    "Park City"
  ],
  "VT": [
    "Burlington",
    "South Burlington",
    "Rutland",
    "Barre",
    "Montpelier",
    "Winooski",
    "St. Albans",
    "Brattleboro"
  ],
  "VA": [
    "Virginia Beach",
    "Chesapeake",
    "Norfolk",
    "Richmond",
    "Newport News",
    "Alexandria",
    "Hampton",
    "Roanoke",
    "Portsmouth",
    "Suffolk",
    "Charlottesville",
    "Williamsburg",
    "Arlington"
  ],
  "WA": [
    "Seattle",
    "Spokane",
    "Tacoma",
    "Vancouver",
    "Bellevue",
    "Kent",
    "Everett",
    "Renton",
    "Yakima",
    "Bellingham",
    "Olympia",
    "Walla Walla"
  ],
  "WV": [
    "Charleston",
    "Huntington",
    "Morgantown",
    "Parkersburg",
    "Wheeling",
    "Weirton",
    "Fairmont",
    "Beckley",
    "Harpers Ferry"
  ],
  "WI": [
    "Milwaukee",
    "Madison",
    "Green Bay",
    "Kenosha",
    "Racine",
    "Appleton",
    "Waukesha",
    "Eau Claire",
    "Oshkosh",
    "La Crosse",
    "Wisconsin Dells"
  ],
  "WY": [
    "Cheyenne",
    "Casper",
    "Laramie",
    "Gillette",
    "Rock Springs",
    "Sheridan",
    "Jackson",
    "Evanston",
    "Cody"
  ]
};
const STATE_NAMES = {
  "AL": "Alabama",
  "AK": "Alaska",
  "AZ": "Arizona",
  "AR": "Arkansas",
  "CA": "California",
  "CO": "Colorado",
  "CT": "Connecticut",
  "DE": "Delaware",
  "FL": "Florida",
  "GA": "Georgia",
  "HI": "Hawaii",
  "ID": "Idaho",
  "IL": "Illinois",
  "IN": "Indiana",
  "IA": "Iowa",
  "KS": "Kansas",
  "KY": "Kentucky",
  "LA": "Louisiana",
  "ME": "Maine",
  "MD": "Maryland",
  "MA": "Massachusetts",
  "MI": "Michigan",
  "MN": "Minnesota",
  "MS": "Mississippi",
  "MO": "Missouri",
  "MT": "Montana",
  "NE": "Nebraska",
  "NV": "Nevada",
  "NH": "New Hampshire",
  "NJ": "New Jersey",
  "NM": "New Mexico",
  "NY": "New York",
  "NC": "North Carolina",
  "ND": "North Dakota",
  "OH": "Ohio",
  "OK": "Oklahoma",
  "OR": "Oregon",
  "PA": "Pennsylvania",
  "RI": "Rhode Island",
  "SC": "South Carolina",
  "SD": "South Dakota",
  "TN": "Tennessee",
  "TX": "Texas",
  "UT": "Utah",
  "VT": "Vermont",
  "VA": "Virginia",
  "WA": "Washington",
  "WV": "West Virginia",
  "WI": "Wisconsin",
  "WY": "Wyoming",
  "DC": "District of Columbia"
};
